# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: CoderWGB's Blog
subtitle: 'Stay hungry, Stay foolish'
description: ''
keywords: "Hello World"
author: CoderWGB
language: zh-Hans
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://WangGuibin/github.io/hexo-github-action
root: /hexo-github-action/
permalink: :year/:month/:day/:title/

menu:
  home: /
  archives: /archives
  about: /about
  categories: /categories
  tags: /tags
 
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: ''
