name: Build HEXO Demo
on: 
   push:
     branches:
       - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: renzhaosy/hexo-deploy-action@master 
      env:
        PERS0NAL_T0KEN: ${{ secrets.HEXO_KEY }}
        PUBLISH_REPOSITORY: WangGuibin/hexo-github-action  
        BRANCH: gh-pages  
        PUBLISH_DIR: ./public  
