name: Deploy to Remote Branch

on:
  push:
    branches:
      - master
      
jobs:
  hexo-deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: hexo-deploy-gh-pages
      uses: khanhicetea/gh-actions-hexo-deploy-gh-pages@master
      env:
        GITHUB_REMOTE_REPOSITORY: WangGuibin/hexo-github-action
        GITHUB_BRANCH: gh-pages 
        GIT_DEPLOY_KEY: ${{ secrets.HEXO_KEY }}
        HUGO_VERSION: "0.58.3"